### ISSUE TITLE
Add examples of using the package to README.md

### ISSUE THREAD

**Issue by MrJGao** [ncsuSEAL/Bayesian_LSP#10]
I feel like it might be easier for users to find the usage of the package if we add examples to README.md. But for now, I'm not sure how to write R Markdown in the README.md, or it just can't be done that way and we have to run an R Markdown to get results and pictures and put them in the README.md manually.

**Comment by mcgregorian1** [comment]
In general, examples are done by showing the code written but then manually inserting screenshots of the results. I think the options are to do this or say if you want more details, please see the vignette

**Comment by MrJGao** [comment]
Ok, yeah, makes sense. I added some notes saying that "if you want to see the examples, please use `help(package = "blsp")` to see the vignettes. I'll close this.
