### ISSUE TITLE
The FitBLSP results

### ISSUE THREAD

**Issue by ghost** [ncsuSEAL/Bayesian_LSP#12]
### The results of FitBLSP function do not show phenology for each year from my own data.
```r
library(blsp)  
library(data.table)  
sample_file <- fread("sampleData.csv")  
single_ts <- sample_file[id == 0, .(date, evi2)]  
single_ts <- na.omit(single_ts)  
head(single_ts)  
avg_fit <- FitAvgModel(
  date_vec = single_ts$date,
  vi_vec = single_ts$evi2
)  

results <- FitBLSP(
  date_vec = single_ts$date,
  vi_vec = single_ts$evi2,
  initValues = avg_fit,
  verbose = TRUE
)  
head(results$phenos)
```
I would like to consult you on this issue, please reply to me at your convenience and thank you for your excellent work.

![c7c25fd0a7dae455af00aa3c78b61ba](https://user-images.githubusercontent.com/77730185/192093487-faa2a7e6-63b2-4ff6-a3b3-c8d3ff9bbc1b.jpg)
[sampleData.csv](https://github.com/ncsuSEAL/Bayesian_LSP/files/9638489/sampleData.csv)

**Comment by MrJGao** [comment]
Thanks for your interest and feedback. I checked your data, it seems this point time series has many "amplitude too low" years (see the image below, in some years, the amplitudes are around 0.1). We intentionally suppress the phenometrics retrieved from these years b/c we are not confident that the EVI2 signal is accurate enough considering the signal-to-noise ratio. Currently, we use an emperical threshold of 0.4 for the parameter `m2`, indicating an amplitude of ~0.15 depending on `m7` (the speed of canopy greendown in the summer). In the future, we may consider let users to configure the threshold. For now, I'd suggest you ignore those years.

Another thing I noticed is that there are several years having significantly large amplitudes than most other years. This problem plus the above problem could confuse the BLSP algorithm to find an overall good fit for all years as it borrows information from other years. I think you can tell it takes a relatively long time for the BLSP algorithm to converge. But, to fix this problem, you can mannually remove these "abnormal" years before fitting the BLSP model. 

I hope this information is helpful. Overall, I'd have to say, be cautious of the retrieved phenometrics for this time series. 

![image](https://user-images.githubusercontent.com/7261090/192113645-5b2f7585-2cac-4dc8-a3cc-988bae824294.png)

**Comment by ghost** [comment]
Thanks for your detailed reply, your comment is very helpful.
