### ISSUE TITLE
Recommendations for pre-release

### ISSUE THREAD

**Issue by mcgregorian1** [ncsuSEAL/Bayesian_LSP#4]
I'm adding recommendations here to keep track of them. I don't want to implement these myself without asking for input.

I'll add to this list as we get closer to having a final package and documentation.
- [x] change the name of `test_ts` to something like `landsatEVI` or `testData` or something? Maybe not necessary, I was just thinking of having the name be more informative since `ts` is an abbreviation that not everyone uses
- [x] `test_ts` only needs columns `date`, rename`all_evi` to `evi`, rename `all_qa` to `pixelQA`, rename `all_from` to `source`, and `snow`.
- [x] #6
- [x] relatedly to above, suggest having a shorter dataset to have for the vignette. It currently takes >3 minutes to run `FitBLSP()` when having the plot, so might be easier for rendering the vignette to just have maybe 10 years worth of data and then at the end I can add a png of what the full thing looks like. 
  - also this would help users be able to run a small sample of the data without this taking a long time
- [x] remove functionality in `Fit_BLSP` where `weights_vec` can be TRUE/FALSE
- [x] #9
  - First, throw error if `weights_vec` is not numeric or is outside of range [0,1]
  - Second, throw error if `weights_vec` is not the same length as `vi_vec`

**Comment by MrJGao** [comment]
1. Changed `test_ts` to `landsatEVI2`.
2. Removed unnecessary columns and renamed `all_evi` column to `evi2`.

**Comment by MrJGao** [comment]
The changes might affect other places, for example, the vignette and other documentation. Please make changes at those places as well.

**Comment by MrJGao** [comment]
3. Progress bar has been added.

**Comment by mcgregorian1** [comment]
> 3. Progress bar has been added.

There are two subsections of the progress bar that does not have a label (under Sampling). Is that on purpose? Are those different parts of the sampling? If not, I recommend these also be labeled.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/39522449/169151963-20868cfd-1bd5-4e98-a5ea-79dfeb487f90.png">

**Comment by mcgregorian1** [comment]
Also suggestion to not have just [1], [1], etc, and instead say 1/5, 2/5, etc? Not sure if this is possible.

**Comment by MrJGao** [comment]
MCMC sampling could have multiple chains, that's why there are multiple progress bars under "Start sampling". I don't think I can control that but I changed the message to "Sampling (could have multiple chains)..." to notify the user.

As the "[1]"s in the output, I figured I could use `message()` instead of `print()` to avoid that problem. So, it's done! See ae1a43a524a495c49d198d2516f896d97f07c005.

**Comment by MrJGao** [comment]
For reducing the computing time of fitting the example time series, in the vignettes, I changed the input data to only use observations from 1984 to 1994, and I moved model visualization out of the modeling fitting process. Now fitting the example data takes less time. See 8275d183585b2cfb719a7b982b46619708f56aca

**Comment by mcgregorian1** [comment]
This all sounds and looks good on my end. If we think of other things later let's open a new issue
